let TOP_MOVIES = "TOP_MOVIES";
let ALL_MOVIES = "ALL_MOVIES";
let FILTER_TO_GENRE = "FILTER_TO_GENRE";
let GET_GENRE = "GET_GENRE";
let GET_INFO = "GET_INFO";
let NEX_PAGE = "NEX_PAGE";
let PREVIOUS_PAGE = "PREVIOUS_PAGE";
let SEARCH_MOVIE = "SEARCH_MOVIE"

export {TOP_MOVIES, ALL_MOVIES, FILTER_TO_GENRE, GET_GENRE, GET_INFO, NEX_PAGE, PREVIOUS_PAGE, SEARCH_MOVIE}